In [1]:
import numpy as np

In [2]:
a = np.array([1, 3])
b = np.array([2, 4])

In [3]:
x1 = np.dot(a, b)
x1

14

In [6]:
import numpy as np
from datetime import datetime as dt

a = np.random.randn(100)
b = np.random.randn(100)
T = 10000

def slow_dot_product(a, b):
    result = 0
    for e, f in zip(a, b):
        result += e * f
    return result

t0 = dt.now()
for t in range(T):
    slow_dot_product(a, b)
dt1 = dt.now() - t0

t0 = dt.now()
for t in range(T):
    a.dot(b)
dt2 = dt.now() - t0

print('dt1 / dt2', dt1.total_seconds() / dt2.total_seconds())
print("Numpy dot product is much faster than a for a loop")

dt1 / dt2 2.3320982874162324
Numpy dot product is much faster than a for a loop


In [7]:
m = np.array([[1, 2], [3, 4]])
l = [[1, 2], [3, 4]]
m

array([[1, 2],
       [3, 4]])

In [8]:
l[0]
l

[[1, 2], [3, 4]]

In [9]:
l[0][0]
l

[[1, 2], [3, 4]]

In [10]:
m[0][0]
m

array([[1, 2],
       [3, 4]])

In [11]:
m[0, 0]

1

In [12]:
m1 = np.matrix([[2, 2], [3, 4]])
m1

matrix([[2, 2],
        [3, 4]])

In [13]:
m2 = np.array(m1)
m2

array([[2, 2],
       [3, 4]])

In [14]:
m2.T

array([[2, 3],
       [2, 4]])

In [15]:
z = np.zeros(10, dtype=int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
p = np.zeros((10, 19), dtype=int)
p

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
random_matrix = np.random.random((10, 10))
random_matrix

array([[ 0.5483327 ,  0.03342977,  0.5570727 ,  0.83347117,  0.84306221,
         0.90868756,  0.85579107,  0.90091974,  0.03292002,  0.98056343],
       [ 0.68579678,  0.22517154,  0.95851108,  0.08534167,  0.2978857 ,
         0.86875612,  0.74389464,  0.37189989,  0.91500092,  0.36770977],
       [ 0.3776648 ,  0.5700829 ,  0.19724265,  0.09297459,  0.72663033,
         0.52725676,  0.17537684,  0.15395317,  0.31194208,  0.51867963],
       [ 0.51681118,  0.09703723,  0.47921927,  0.58527088,  0.89068363,
         0.43807119,  0.7954382 ,  0.43540713,  0.5188661 ,  0.6413674 ],
       [ 0.51793164,  0.03060994,  0.42159079,  0.59579675,  0.51036256,
         0.61545305,  0.71473292,  0.82938842,  0.00867244,  0.11614715],
       [ 0.20904914,  0.6438408 ,  0.0518282 ,  0.71347104,  0.35681422,
         0.82256526,  0.90571814,  0.20418914,  0.35625908,  0.41211041],
       [ 0.95744718,  0.59334031,  0.81487744,  0.61493534,  0.83228261,
         0.11468494,  0.9840446 ,  0.92952415

In [19]:
g = np.random.randn(4, 4)
g

array([[-0.2489602 , -0.48450344,  1.43641111,  0.13971084],
       [ 1.33382565, -0.78410446,  0.10309447, -1.15550981],
       [-0.62988218,  0.05893081,  1.06165382, -0.09261445],
       [ 1.20290512, -0.76658769,  0.08520687, -1.02782261]])

In [21]:
mean = g.mean()
mean

0.014484614403144677

In [22]:
variance = g.var()
variance

0.67188334729350729